name: Deploy NuGet

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Extract version from .csproj
      id: version
      shell: pwsh
      run: |
        $csprojPath = '<SahringMessages>.csproj'
        $version = Select-String -Path $csprojPath -Pattern '<Version>(.*?)</Version>' | ForEach-Object { $_.Matches.Groups[1].Value }
        echo "##[set-output name=VERSION;]$version"

    - name: Pack NuGet package
      run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.version.outputs.VERSION }} --no-build --output ./nupkg

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
